### ISSUE TITLE
Suggestions: Fix .py header and update Spoofing exception to catch all the possible dnspython errors.

### ISSUE THREAD

**Issue by 0CM** [B0lg0r0v/Elyzer#3]
#!python3
# -*- coding: utf-8 -*-

line 429:
except (dns.resolver.LifetimeTimeout, dns.resolver.NoAnswer,dns.resolver.NXDOMAIN,dns.resolver.YXDOMAIN,dns.resolver.NoNameservers):
        print(f'{Fore.LIGHTRED_EX}Could not resolve the MX Record.{Fore.RESET}')

Nice tool!

**Comment by mochabyte0x** [comment]
Hi, thank you for pointing that out ! I just extended the exception.

Glad you liked the tool !
