### ISSUE TITLE
Suggestion: New switch to disable the DNS check

### ISSUE THREAD

**Issue by 0CM** [B0lg0r0v/Elyzer#4]
Would you please consider adding a arg switch to the script to disable/suspend DNS domain check in the "Spoofing Function" ?
It's not good practice to actively probe IP and Domains associated with targeted phis attempts.  

Thank you

**Comment by mochabyte0x** [comment]
Hi, thanks for pointing that out ! But which part of the code should *not* do the DNS checks ? The spoofing / phishing function heavily relies on resolving MX, TXT and A records in order to compare values. Disabling some checks could impact the functions behavior.

**Comment by 0CM** [comment]
I like to be able to suspend all of the active probing, 

yes it may impact the results, or you can use virustotal to query their DB with DNS records. 

->  Disable | Passive via VT | Full active via PyDNS.

VT example:
https://www.virustotal.com/gui/domain/binarybandits.org/details

The main point is not to show your hand and let the phish sender know, that it's being investigated.
Not too much trouble when it opportunistic phis email, but not advisable when it is something targeted.

**Comment by mochabyte0x** [comment]
Thanks for the ideas. I could add a switch for "passive" or "indirect" DNS checks via VT or via some kind of proxys. I'll write that on my to-do list !

**Comment by mochabyte0x** [comment]
Hi, the requested features have now been implemented in v0.4.0.

**Comment by 0CM** [comment]
Splendid, thank you very much, will test it out next week and will add it to my distro. 
Have a nice weekend.
